### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [LittleColin/Cake.Apigee#2]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by gep13** [comment]
@LittleColin just wanted to follow up to see if you had had a chance to give this some thought.  Thanks!

**Comment by LittleColin** [comment]
Sorry completely missed this. Great suggestion and thank you for the guidance - will have a go this weekend.

**Comment by gep13** [comment]
@LittleColin perfect! Let me know if you have any questions.

**Comment by LittleColin** [comment]
@gep13 Create pull request https://github.com/cake-build/website/pull/333 - hope this is ok

**Comment by gep13** [comment]
@LittleColin nice one! Thank you very much for adding this! 👍

**Comment by LittleColin** [comment]
@gep13 I was wondering if you knew why the documentation wasn't being picked up on the Cake site?

https://github.com/LittleColin/Cake.Apigee/blob/master/src/Cake.Apigee/Cake.Apigee.xml
http://cakebuild.net/api/Cake.Apigee/ApigeeAliases/

Your assistance much appreciated

**Comment by gep13** [comment]
@LittleColin the XML file in your nupkg file, which is published to NuGet.org doesn't actually contain any documentation:

![image](https://cloud.githubusercontent.com/assets/1271146/25236172/17de803c-25df-11e7-9998-ff02fc683200.png)

The website uses the version that is packaged up in the nupkg file.

**Comment by LittleColin** [comment]
Ah thanks @gep13  - I had incorrectly assumed it took the documentation from github rather than nuget. I have republished the nuget package as v0.8 which includes the updated documentation. Will this be automatically picked up by the Cake website?

**Comment by gep13** [comment]
@LittleColin this will be picked up the next time we publish the website, which typically happens at least once a week.

**Comment by LittleColin** [comment]
I see it's just been updated and comments now appear at http://cakebuild.net/api/Cake.Apigee/ApigeeAliases/

**Comment by gep13** [comment]
Sweet! 👍
