### ISSUE TITLE
Use Validate flag when calling Apigee

### ISSUE THREAD

**Issue by andywilsonuk** [LittleColin/Cake.Apigee#4]
Hi LittleColin,

I'm about to start using your Cake add-in for integration with Apigee however I've noticed from the documentation that Apigee can validate packages being imported; I find this very useful because there is no XSD schema available (I would also assume it would perform more validation around matching names and file/folder structure).

Would it be possible for you to modify the ApigeeProxyManagementService class to send the parameter as described here: http://docs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/apis-0 ideally it would be on by default but I suppose it could be a property of ImportProxySettings.

Many thanks 
Andy

**Comment by LittleColin** [comment]
Thanks for the suggestion Andy, I didn't know about that flag - looks like it should be the default. I'll add it to the ImportProxySettings defaulted to true so it can be set to false if it causes problems for someone. Hopefully get round to this in the next couple of days.

**Comment by LittleColin** [comment]
Done - this is resolved in 0.12.0.

**Comment by andywilsonuk** [comment]
Great! 

Many thanks.
Andy
